CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE INDEX hotels_name_lower_idx ON hotels (LOWER(name));

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL REFERENCES hotels (id) ON DELETE CASCADE,
    number TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('single', 'double', 'deluxe')),
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    UNIQUE (hotel_id, number)
);

CREATE TABLE bookings (
    reference TEXT PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms (id) ON DELETE RESTRICT,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests INTEGER NOT NULL CHECK (guests > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (check_in < check_out),
    CONSTRAINT bookings_no_overlapping_stays
        EXCLUDE USING gist (
            room_id WITH =,
            daterange(check_in, check_out, '[)') WITH &&
        )
);
